---
- name: Install and Configure Nginx
  hosts: web
  become: yes

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
